### PR TITLE
Adding labels to roads (proposal)

### PR DESCRIPTION
**Pull request by aklofas**
Include calculations to repeat road names for long roads

### CODE REVIEW

**Comment by aklofas** [comment]
Example of the implementation
pineridge

**Comment by enzet** [comment]
Hello, @aklofas!

Wow, this is just wonderful! Thank you for the request.

**Review by enzet — CHANGES_REQUESTED** [review]
I tried to find a solution for determining text width from Python and it seems like some pretty rough approximation is what we want.

**Comment by aklofas** [comment]
Yeah some of the code is messy. This was just a proposal to get the ball rolling on a possible implementation. It's clear that to get this feature implemented right, we'll need:

- Get the real width of the label with font+size
- Add scheme style support
- Ability to switch on and off (argparse?)
- Flip text (or reverse paths) so labels aren't upside down sometimes
- Combine segmented paths for continuous labels (some roads are split several times)
- (optional) avoid putting labels on tight corners
- probably more...

Overall this a ***great*** project and I'm still poking around the code understanding everything you've done. A lot of hard creative work went into this and it really shows!

**Comment by enzet** [comment]
Yeah, the list is almost what I have in mind on this issue. And I think there is a more challenging task to get rid of overlapping between labels by moving them along the lines.

^_^ Thank you very much for such a review! This is really motivating!

**Comment by enzet** [comment]
Hello, @aklofas,

I would really like to merge this request and continue to improve labels for ways.  Could you please fix code style, so that I can do that?

The easiest way is to
  - `pip install black flake8`,
  - run `black -l 80 map_machine`,
  - run `flake8 --max-line-length=80 --ignore=E203,W503 map_machine`,
  - and fix some line lengths.

Thank you!

**Pull request closed without merging**
